#include <stdio.h>
#include "/home/jack/develop/c/lib/datastructs-c/arraylist.h"

arraylist *getallhistory();
/* Default the result which generated by the method would not contain the word which you have known */
arraylist *generaterandomsorthistory();
void writehistory(arraylist *l);

arraylist *loadrandomsorthistory();

arraylist *getallhistory_version2();
